name: pr
on: pull_request
jobs:
  pr:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: olafurpg/setup-scala@v10
      - uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.coursier
          key: ${{ runner.os }}-sbt-${{ hashfiles('**/build.sbt') }}
      - run: sbt test
      - run:
        echo "LATEST_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      - uses: actions/create-release@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            tag_name: ${{ env.LATEST_TAG }}
            release_name: ${{ env.LATEST_TAG }}
            draft: true
            prerelease: false
